<?php
use App\Http\Controllers\Exam\BehavioursController;
use App\Http\Controllers\Exam\EffortLevelsController;
use App\Http\Controllers\Exam\GradingPoliciesController;
use App\Models\PurchaseOrder;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\MealBatchController;
use App\Http\Controllers\Exam\SkillsController;
use App\Http\Controllers\HR\EmployeeController;
use App\Http\Controllers\RequisitionController;
use App\Http\Controllers\Admin\BudgetController;
use App\Http\Controllers\admin\VendorController;
use App\Http\Controllers\Admin\EntriesController;
use App\Http\Controllers\Admin\LedgersController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Inventory\ItemController;
use App\Http\Controllers\admin\InventoryController;
use App\Http\Controllers\Inventory\QuoteController;
use App\Http\Controllers\Academic\TeacherController;
use App\Http\Controllers\Exam\ExamScheduleController;
use App\Http\Controllers\Inventory\ProductController;
use App\Http\Controllers\Inventory\InventryController;
use App\Http\Controllers\Inventory\SupplierController;
use App\Http\Controllers\Academic\SchoolTypeController;
use App\Http\Controllers\Admin\BudgetCategoryController;
use App\Http\Controllers\admin\VendorCategoryController;
use App\Http\Controllers\HR\CalculateComissionController;
use App\Http\Controllers\Inventory\SchoolLunchController;
use App\Http\Controllers\Academic\ActiveSessionController;
use App\Http\Controllers\Inventory\PurchaseOrderController;


Route::group(['middleware' => ['auth'], 'prefix' => 'datatable', 'as' => 'datatable.'], function () {
    Route::post('get-data-user', 'App\Http\Controllers\UserController@getData')->name('get-data-user');
    Route::post('get-data-role', 'App\Http\Controllers\RoleController@getData')->name('get-data-role');
    Route::get('get-data-ledger', [LedgersController::class, 'getData'])->name('get-data-ledger');
    Route::get('get-data-ledger-income', 'App\Http\Controllers\Admin\LedgersController@getDataincome')->name('get-data-ledger-income');
    Route::get('get-data-ledger-receivable', 'App\Http\Controllers\Admin\LedgersController@getDatareciable')->name('get-data-ledger-receivable');
    Route::post('get-data-permission', 'App\Http\Controllers\PermissionController@getData')->name('get-data-permission');
    Route::post('get-data-coursetype', 'App\Http\Controllers\Admin\CourseTypeController@getData')->name('course-type.getdata');
    Route::post('get-data-teachers_data', [TeacherController::class, 'getData'])->name('data.getTeachers');
    Route::post('get-data-teachersData', [\App\Http\Controllers\Academic\ActiveSessionController::class, 'getData'])->name('data.getActiveSession');
    Route::post('get-data-assignClass', [\App\Http\Controllers\Academic\AssignClassController::class, 'getData'])->name('get-data-assignClass');
    Route::post('get-data-studentAttendance', [\App\Http\Controllers\Academic\AttendanceController::class, 'getData'])->name('get-student-Attendance');
    Route::post('get_data_student', 'App\Http\Controllers\Student\StudentController@get_data_student')->name('getStudentData');
    Route::post('get_academic_session', [\App\Http\Controllers\Student\AcademicSessionController::class, 'getData'])->name('academic.getsession');
    Route::post('view_student_data', [\App\Http\Controllers\Academic\StudentViewController::class, 'getData'])->name('getStudentViewData');
    Route::post('get_school_types', [SchoolTypeController::class, 'getData'])->name('schoolTypes.getdata');
    Route::post('get_classes', [\App\Http\Controllers\Academic\ClassController::class, 'getData'])->name('get-data-class');
    Route::post('get_sections', [\App\Http\Controllers\Academic\SectionController::class, 'getData'])->name('get-data-section');
    Route::post('get_timetable', [\App\Http\Controllers\Academic\TimeTableController::class, 'getData'])->name('get-data-timetable');
    Route::post('get_admission_data', 'App\Http\Controllers\Student\StudentDataBankController@getData')->name('getAdmissionData');
    Route::post('get-data-courses', 'App\Http\Controllers\Admin\CourseController@getData')->name('get-data-courses');
    Route::post('get-data-session', 'App\Http\Controllers\Admin\SessionController@getData')->name('get-data-session');
    Route::post('get_data_agent', 'App\Http\Controllers\HR\AgentController@getData')->name('get_data_agent');
    Route::get('get_data_bank_student', 'App\Http\Controllers\Admin\DataBankController@getData')->name('get_data_bank_student');
    Route::post('get_data_company', 'App\Http\Controllers\Admin\CompanyController@getData')->name('company.getdata');
    Route::post('get_data_financial', 'App\Http\Controllers\FinancialController@getData')->name('financial.getdata');
    Route::post('get-data-branch', 'App\Http\Controllers\Admin\BranchController@getData')->name('get-data-branch');
    Route::post('get-data-classTime', [\App\Http\Controllers\Academic\ClassTimeTableController::class, 'getData'])->name('get-data-classTime');
    Route::post('get-data-assigntimeTable', [\App\Http\Controllers\Academic\AssignTimeTableController::class, 'getData'])->name('get-data-assignTime');
    Route::post('get-data-department', 'App\Http\Controllers\Admin\DepartmentController@getData')->name('get-data-department');
    Route::post('get-data-holiday', [\App\Http\Controllers\HR\HolidayController::class, 'getData'])->name('get-data-holiday');
    Route::post('get-studentSibling', [\App\Http\Controllers\Student\StudentController::class, 'getStudentSiblingData'])->name('getStudentSibling');
    Route::post('get-feeFactor', [\App\Http\Controllers\Admin\FeeFactorController::class, 'getData'])->name('fee-factor.getfeeFactor');
    Route::post('get-billGeneration', [\App\Http\Controllers\Admin\BillGenerationController::class, 'getData'])->name('getBillGeneration');
    Route::post('get-bank', [\App\Http\Controllers\Admin\BankController::class, 'getData'])->name('bank.getdata');
    Route::post('get-bankBranch', [\App\Http\Controllers\Admin\BankBranchesController::class, 'getData'])->name('get-data-bank-branch');
    Route::post('get-bankAccount', [\App\Http\Controllers\Admin\BanksAccountController::class, 'getData'])->name('getBanksAccount');
    Route::post('get-examTerm', [\App\Http\Controllers\Exam\ExamTermController::class, 'getData'])->name('getExamTerm');
    Route::post('get-marksInput', [\App\Http\Controllers\Exam\MarksInputController::class, 'getData'])->name('getMarksInput');
    Route::post('get-testType', [\App\Http\Controllers\Exam\TestTypeController::class, 'getData'])->name('test_type.getdata');
    Route::post('get-examDetail', [\App\Http\Controllers\Exam\ExamDetailController::class, 'getData'])->name('getExamDetail');
    Route::post('get-componentDetail', [\App\Http\Controllers\Exam\ComponentController::class, 'getData'])->name('component.getdata');
    Route::post('get-subComponentDetail', [\App\Http\Controllers\Exam\SubComponentController::class, 'getData'])->name('sub-component.getdata');
    Route::post('get-skills', [SkillsController::class, 'getData'])->name('skills.getdata');
    Route::post('get-skillEvaluation', [\App\Http\Controllers\Exam\SkillEvaluationController::class, 'getData'])->name('skill-evaluation.getdata');
    Route::post('get-skillEvaluationKey', [\App\Http\Controllers\Exam\SkillEvaluationKeyController::class, 'getData'])->name('skill-evaluation-key.getdata');
    Route::post('get-behaviours', [BehavioursController::class, 'getData'])->name('behaviours.getdata');
    Route::post('get-effortLevels', [EffortLevelsController::class, 'getData'])->name('effort_levels.getdata');
    Route::post('get-grading_policies', [GradingPoliciesController::class, 'getData'])->name('grading_policies.getdata');
    Route::post('get-academicEvaluation', [\App\Http\Controllers\Exam\AcademicEvaluationController::class, 'getData'])->name('academic-evaluation.getdata');
    Route::post('get-classSubject', [\App\Http\Controllers\Exam\ClassSubjectController::class, 'getData'])->name('classSubject.getdata');
    Route::post('get-skillGroup', [\App\Http\Controllers\Exam\SkillGroupController::class, 'getData'])->name('skill-group.getData');
    Route::post('get-overTime', [\App\Http\Controllers\HR\OvertimeController::class, 'getData'])->name('data.overtimeData');
    Route::post('get-assetType', [\App\Http\Controllers\HR\AssetTypeController::class, 'getData'])->name('data.assetTypeData');
    Route::post('get-asset', [\App\Http\Controllers\HR\AssetController::class, 'getData'])->name('data.assetData');
    Route::post('get-skillType', [\App\Http\Controllers\Exam\SkillTypeController::class, 'getData'])->name('data.skillTypeData');
    Route::get('get_data_student_fee', 'App\Http\Controllers\Fee\StudentFeeController@get_data_student_fee')->name('get_data_student_fee');
    Route::get('get_data_student_paid_fee_detail/{id}', 'App\Http\Controllers\Fee\StudentFeeController@get_data_student_paid_fee_detail')->name('get_data_student_paid_fee_detail');
    Route::get('students_view_specific_installemet/{id}', 'App\Http\Controllers\Admin\DataBankController@students_view_specific_installemet')->name('students_view_specific_installemet');
    Route::post('get_data_teacher', 'App\Http\Controllers\HR\TeacherController@getData')->name('get_data_teacher');
    Route::post('get_data_teacher_session', 'App\Http\Controllers\HR\TeacherAssignSessionController@getData')->name('get_data_teacher_session');
    Route::post('get_data_employee_type', 'App\Http\Controllers\HR\EmployeeTypeController@getData')->name('get_data_employee_type');
    Route::post('get_data_employee', 'App\Http\Controllers\HR\EmployeeController@getData')->name('get_data_employee');
    Route::post('get_employee_payroll', 'App\Http\Controllers\HR\PayrollController@getData')->name('get_employee_payroll');
    Route::GET('get_data_employee_payroll', 'App\Http\Controllers\HR\PayrollController@oldpayroll')->name('get_data_employee_payroll');
    Route::post('get_data_video', 'App\Http\Controllers\Admin\VideoUploadController@getData')->name('get_data_video');
    Route::post('get_data_agent_type', 'App\Http\Controllers\HR\AgentTypeController@getData')->name('get_data_agent_type');
    Route::post('get_data_agent_comission', 'App\Http\Controllers\HR\AgentCommissionController@getData')->name('get_data_agent_comission');
    Route::post('get_employee_attendance', 'App\Http\Controllers\HR\EmployeeController@get_employee_attendance')->name('get_employee_attendance');
    Route::post('get_data_employee_leaves', 'App\Http\Controllers\HR\EmployeeLeavesController@getData')->name('get_data_employee_leaves');
    Route::post('get-video-category', 'App\Http\Controllers\Admin\VideoCategoryController@getData')->name('get-video-category');
    Route::post('old_commission_getdata', [CalculateComissionController::class, 'old_commission_getdata'])->name('old_commission_getdata');
    Route::post('get_agent_comission', [CalculateComissionController::class, 'get_agent_comission'])->name('get_agent_comission');
    Route::post('get_data_student_fee_more_than_30k', [\App\Http\Controllers\Fee\StudentFeeController::class, 'get_data_student_fee_more_than_30k'])->name('get_data_student_fee_more_than_30k');
    Route::post('get_data_old_assign_tools/{id}', [\App\Http\Controllers\Admin\ToolsController::class, 'get_data_old_assign_tools'])->name('get_data_old_assign_tools');
    Route::post('get_data_tools_tool', [\App\Http\Controllers\Admin\ToolsController::class, 'get_data_tools_tool'])->name('get_data_tools_tool');
    Route::post('bv_form_get_data', [\App\Http\Controllers\Admin\DataBankController::class, 'bv_form_get_data'])->name('bv_form_get_data');
    Route::post('seminar_form_get_data', [\App\Http\Controllers\Admin\DataBankController::class, 'seminar_form_get_data'])->name('seminar_form_get_data');
    Route::post('onezcamp_form_get_data', [\App\Http\Controllers\Admin\DataBankController::class, 'onezcamp_form_get_data'])->name('onezcamp_form_get_data');
    Route::get('get_data_fee_collection', [\App\Http\Controllers\Admin\LedgersController::class, 'get_data_fee_collection'])->name('get_data_fee_collection');
    //    Route::get('entries/getData', [EntriesController::class, 'getData'])->name('entries.getData');
    Route::post('get_data_department', [\App\Http\Controllers\HR\DepartmentController::class, 'get_data_department'])->name('get_data_department');
    Route::post('new_sale_incentive_get', [\App\Http\Controllers\HR\CalculateComissionController::class, 'get_data_new_sales'])->name('new_sale_incentive_get');
    Route::post('new_recovery_incentive_get', [\App\Http\Controllers\HR\CalculateComissionController::class, 'get_data_new_recovery'])->name('new_recovery_incentive_get');
    Route::post('get-category', [CategoryController::class, 'getData'])->name('category.getdata');
    Route::post('get-account-head', [\App\Http\Controllers\Admin\AccountHeadController::class, 'getData'])->name('account-head.getdata');
    //    fee section
    Route::post('get-fee-section', [\App\Http\Controllers\Admin\FeeSectionController::class, 'getData'])->name('getFeeSection');
    Route::post('get-fee-heads', [\App\Http\Controllers\Admin\FeeHeadController::class, 'getData'])->name('getFeeHeads');
    Route::post('get-fee-structure', [\App\Http\Controllers\Admin\FeeStructureController::class, 'getData'])->name('getFeeStructure');
    Route::post('get-fee-term', [\App\Http\Controllers\Admin\FeeTermController::class, 'getData'])->name('getFeeTerm');
    Route::post('get-fee-category', [\App\Http\Controllers\Admin\FeeCategoryController::class, 'getData'])->name('getFeeCategory');
    Route::post('get-fee-student', [\App\Http\Controllers\Admin\StudentFeeController::class, 'getData'])->name('getStudentFee');
    Route::post('get-designation', [\App\Http\Controllers\HR\DesignationController::class, 'getData'])->name('designations.getdata');
    Route::post('get-quota', [\App\Http\Controllers\HR\QuottaController::class, 'getData'])->name('quota.getdata');
    Route::post('get-work_shift', [\App\Http\Controllers\HR\workShiftController::class, 'getData'])->name('workshift.getdata');
    Route::post('get-leave-request', [\App\Http\Controllers\HR\LeaveRequestController::class, 'getData'])->name('leave_request.getdata');
    Route::post('get-leaves', [\App\Http\Controllers\HR\ManageLeaveController::class, 'getData'])->name('manage.leaves.getdata');
    Route::post('get-attendance', [\App\Http\Controllers\HR\AttendanceController::class, 'getData'])->name('attendance.getAttendance');
    Route::post('get-rentalTax', [\App\Http\Controllers\HR\TaxSlabController::class, 'getData'])->name('rentalTax.get_data_rentalTax');
    Route::post('get-salaryTax', [\App\Http\Controllers\HR\SalaryTaxController::class, 'getData'])->name('salaryTax.get_salaryTax');
    Route::post('get-eobiData', [\App\Http\Controllers\HR\EobiController::class, 'getData'])->name('data.eobiData');
    Route::post('get-profitData', [\App\Http\Controllers\HR\ProfitFundController::class, 'getData'])->name('data.profitData');
    Route::post('get-allowance', [\App\Http\Controllers\HR\AllowanceController::class, 'getData'])->name('allowance.getdata');
    Route::post('get-social', [\App\Http\Controllers\HR\SocialSecurityController::class, 'getData'])->name('data.socialSecurityData');
    Route::post('get-advances', [\App\Http\Controllers\HR\AdvanceController::class, 'getData'])->name('data.advancesData');
    Route::post('get-advanceApproval', [\App\Http\Controllers\HR\AdvanceApprovalController::class, 'getData'])->name('data.advanceApproval');
    Route::post('get-employeeWelfare', [\App\Http\Controllers\HR\EmployeeWelfareController::class, 'getData'])->name('data.welfareData');
    Route::post('get-payrollApproval', [\App\Http\Controllers\HR\PayrollApprovalController::class, 'getData'])->name('data.payroll.approvalDatatable');
    Route::post('get-payrollSlip', [\App\Http\Controllers\HR\PaySlipController::class, 'getData'])->name('data.payroll.slip');
    Route::post('get-items', [ItemController::class, 'getData'])->name('data.items');
    Route::post('get-suppliers', [SupplierController::class, 'getData'])->name('data.suppliers');
    Route::post('get-requisitions', [RequisitionController::class, 'getData'])->name('data.requisitions');
    Route::post('get-quotes', [QuoteController::class, 'getData'])->name('data.quotes');
    Route::post('get-purchaseOrder', [PurchaseOrderController::class, 'getData'])->name('data.purchaseOrder');
    Route::post('get-inventory', [InventryController::class, 'getData'])->name('data.inventory');
    Route::post('get-products', [ProductController::class, 'getData'])->name('data.product');
    Route::post('get-completedGoods', [ProductController::class, 'getCompleted'])->name('data.getCompleted');
    Route::post('get-lunchAssigned', [MealBatchController::class, 'getAssigned'])->name('data.getAssigned');
    Route::post('get-empLunchAssigned', [MealBatchController::class, 'empGetAssigned'])->name('data.empGetAssigned');

    Route::post('/datatable/exam-schedules', [ExamScheduleController::class, 'getData'])->name('getExamSchedule');

    Route::post('get-data-budget', [BudgetController::class, 'getData'])->name('get-data-budget');
    Route::post('get-data-category', [BudgetCategoryController::class, 'getData'])->name('get-data-category');
    
    Route::post('get-vendor-category', [VendorCategoryController::class, 'getData'])->name('get-vendor-category');
    Route::post('get-vendors', [VendorController::class, 'index'])->name('get-vendors');
    Route::post('get-inventorys', [InventoryController::class, 'index'])->name('get-inventorys');

});
