<?php
use App\Http\Controllers\Exam\BehavioursController;
use App\Http\Controllers\Exam\EffortLevelsController;
use App\Http\Controllers\Exam\GradingPoliciesController;
use App\Models\PurchaseOrder;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\MealBatchController;
use App\Http\Controllers\Exam\SkillsController;
use App\Http\Controllers\HR\EmployeeController;
use App\Http\Controllers\RequisitionController;
use App\Http\Controllers\Admin\BudgetController;
use App\Http\Controllers\admin\VendorController;
use App\Http\Controllers\Admin\EntriesController;
use App\Http\Controllers\Admin\LedgersController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Inventory\ItemController;
use App\Http\Controllers\admin\InventoryController;
use App\Http\Controllers\Inventory\QuoteController;
use App\Http\Controllers\Academic\TeacherController;
use App\Http\Controllers\Exam\ExamScheduleController;
use App\Http\Controllers\Inventory\ProductController;
use App\Http\Controllers\Inventory\InventryController;
use App\Http\Controllers\Inventory\SupplierController;
use App\Http\Controllers\Academic\SchoolTypeController;
use App\Http\Controllers\Admin\BudgetCategoryController;
use App\Http\Controllers\admin\VendorCategoryController;
use App\Http\Controllers\HR\CalculateComissionController;
use App\Http\Controllers\Inventory\SchoolLunchController;
use App\Http\Controllers\Academic\ActiveSessionController;
use App\Http\Controllers\Inventory\PurchaseOrderController;


Route::group(['middleware' => ['auth'], 'prefix' => 'datatable', 'as' => 'datatable.'], function () {
    Route::post('get-data-user', 'App\Http\Controllers\UserController@getData')->name('get-data-user');
    Route::post('get-data-role', 'App\Http\Controllers\RoleController@getData')->name('get-data-role');
    Route::get('get-data-ledger', [LedgersController::class, 'getData'])->name('get-data-ledger');
    Route::get('get-data-ledger-income', 'App\Http\Controllers\Admin\LedgersController@getDataincome')->name('get-data-ledger-income');
    Route::get('get-data-ledger-receivable', 'App\Http\Controllers\Admin\LedgersController@getDatareciable')->name('get-data-ledger-receivable');
    Route::post('get-data-permission', 'App\Http\Controllers\PermissionController@getData')->name('get-data-permission');
    Route::post('get-data-coursetype', 'App\Http\Controllers\Admin\CourseTypeController@getData')->name('course-type.getdata');
    Route::post('category/getdata', 'App\Http\Controllers\Admin\CategoryController@getdata')->name('category.getdata');
    Route::post('getExamTerm', 'App\Http\Controllers\Exam\ExamTermController@getData')->name('getExamTerm');
    Route::post('test_type/getdata', 'App\Http\Controllers\Exam\TestTypeController@getData')->name('test_type.getdata');
    Route::post('get-data-teachers_data', [TeacherController::class, 'getData'])->name('data.getTeachers');
    Route::post('get-data-teachersData', [\App\Http\Controllers\Academic\ActiveSessionController::class, 'getData'])->name('data.getActiveSession');
    Route::post('get-data-assignClass', [\App\Http\Controllers\Academic\AssignClassController::class, 'getData'])->name('get-data-assignClass');
    Route::post('get-data-studentAttendance', [\App\Http\Controllers\Academic\AttendanceController::class, 'getData'])->name('get-student-Attendance');
    Route::post('get_data_student', 'App\Http\Controllers\Student\StudentController@get_data_student')->name('getStudentData');
    Route::post('get_academic_session', [\App\Http\Controllers\Student\AcademicSessionController::class, 'getData'])->name('academic.getsession');
    Route::post('view_student_data', [\App\Http\Controllers\Academic\StudentViewController::class, 'getData'])->name('getStudentViewData');
    Route::post('get_school_types', [SchoolTypeController::class, 'getData'])->name('schoolTypes.getdata');
    Route::post('get_classes', [\App\Http\Controllers\Academic\ClassController::class, 'getData'])->name('get-data-class');
    Route::post('get_sections', [\App\Http\Controllers\Academic\SectionController::class, 'getData'])->name('get-data-section');
    Route::post('get_timetable', [\App\Http\Controllers\Academic\TimeTableController::class, 'getData'])->name('get-data-timetable');
    Route::post('get_admission_data', 'App\Http\Controllers\Student\StudentDataBankController@getData')->name('getAdmissionData');
    Route::post('get-data-courses', 'App\Http\Controllers\Admin\CourseController@getData')->name('get-data-courses');
    Route::post('get-data-session', 'App\Http\Controllers\Admin\SessionController@getData')->name('get-data-session');
    Route::post('get_data_agent', 'App\Http\Controllers\HR\AgentController@getData')->name('get_data_agent');
    Route::get('get_data_bank_student', 'App\Http\Controllers\Admin\DataBankController@getData')->name('get_data_bank_student');
    Route::post('get_data_company', 'App\Http\Controllers\Admin\CompanyController@getData')->name('company.getdata');
    Route::post('get_data_financial', 'App\Http\Controllers\FinancialController@getData')->name('financial.getdata');
    Route::post('get-data-branch', 'App\Http\Controllers\Admin\BranchController@getData')->name('get-data-branch');
    Route::post('get-data-classTime', [\App\Http\Controllers\Academic\ClassTimeTableController::class, 'getData'])->name('get-data-classTime');
    Route::post('get-data-assigntimeTable', [\App\Http\Controllers\Academic\AssignTimeTableController::class, 'getData'])->name('get-data-assignTime');
    Route::post('get-data-department', 'App\Http\Controllers\Admin\DepartmentController@getData')->name('get-data-department');
    Route::post('get-data-holiday', [\App\Http\Controllers\HR\HolidayController::class, 'getData'])->name('get-data-holiday');
    Route::post('get-studentSibling', [\App\Http\Controllers\Student\StudentController::class, 'getStudentSiblingData'])->name('getStudentSibling');
    Route::post('get-designation', [\App\Http\Controllers\HR\DesignationController::class, 'getData'])->name('designations.getdata');
    Route::post('get-quota', [\App\Http\Controllers\HR\QuottaController::class, 'getData'])->name('quota.getdata');
    Route::post('get-work_shift', [\App\Http\Controllers\HR\workShiftController::class, 'getData'])->name('workshift.getdata');
    Route::post('get-leave-request', [\App\Http\Controllers\HR\LeaveRequestController::class, 'getData'])->name('leave_request.getdata');
    Route::post('get-leaves', [\App\Http\Controllers\HR\ManageLeaveController::class, 'getData'])->name('manage.leaves.getdata');
    Route::post('get-attendance', [\App\Http\Controllers\HR\AttendanceController::class, 'getData'])->name('attendance.getAttendance');
    Route::post('get-rentalTax', [\App\Http\Controllers\HR\TaxSlabController::class, 'getData'])->name('rentalTax.get_data_rentalTax');
    Route::post('get-salaryTax', [\App\Http\Controllers\HR\SalaryTaxController::class, 'getData'])->name('salaryTax.get_salaryTax');
    Route::post('get-eobiData', [\App\Http\Controllers\HR\EobiController::class, 'getData'])->name('data.eobiData');
    Route::post('get-profitData', [\App\Http\Controllers\HR\ProfitFundController::class, 'getData'])->name('data.profitData');
    Route::post('get-allowance', [\App\Http\Controllers\HR\AllowanceController::class, 'getData'])->name('allowance.getdata');
    Route::post('get-social', [\App\Http\Controllers\HR\SocialSecurityController::class, 'getData'])->name('data.socialSecurityData');
    Route::post('get-advances', [\App\Http\Controllers\HR\AdvanceController::class, 'getData'])->name('data.advancesData');
    Route::post('get-advanceApproval', [\App\Http\Controllers\HR\AdvanceApprovalController::class, 'getData'])->name('data.advanceApproval');
    Route::post('get-employeeWelfare', [\App\Http\Controllers\HR\EmployeeWelfareController::class, 'getData'])->name('data.welfareData');
    Route::post('get-payrollApproval', [\App\Http\Controllers\HR\PayrollApprovalController::class, 'getData'])->name('data.payroll.approvalDatatable');
    Route::post('get-payrollSlip', [\App\Http\Controllers\HR\PaySlipController::class, 'getData'])->name('data.payroll.slip');
    Route::post('get-items', [ItemController::class, 'getData'])->name('data.items');
    Route::post('get-suppliers', [SupplierController::class, 'getData'])->name('data.suppliers');
    Route::post('get-requisitions', [RequisitionController::class, 'getData'])->name('data.requisitions');
    Route::post('get-quotes', [QuoteController::class, 'getData'])->name('data.quotes');
    Route::post('get-purchaseOrder', [PurchaseOrderController::class, 'getData'])->name('data.purchaseOrder');
    Route::post('get-inventory', [InventryController::class, 'getData'])->name('data.inventory');
    Route::post('get-products', [ProductController::class, 'getData'])->name('data.product');
    Route::post('get-completedGoods', [ProductController::class, 'getCompleted'])->name('data.getCompleted');
    Route::post('get-lunchAssigned', [MealBatchController::class, 'getAssigned'])->name('data.getAssigned');
    Route::post('get-empLunchAssigned', [MealBatchController::class, 'empGetAssigned'])->name('data.empGetAssigned');

    Route::post('/datatable/exam-schedules', [ExamScheduleController::class, 'getData'])->name('getExamSchedule');

    Route::post('get-data-budget', [BudgetController::class, 'getData'])->name('get-data-budget');
    Route::post('get-data-category', [BudgetCategoryController::class, 'getData'])->name('get-data-category');
    
    Route::post('get-vendor-category', [VendorCategoryController::class, 'getData'])->name('get-vendor-category');
    Route::post('get-vendors', [VendorController::class, 'index'])->name('get-vendors');
    Route::post('get-inventorys', [InventoryController::class, 'index'])->name('get-inventorys');
    Route::post('skills/getdata', [\App\Http\Controllers\Exam\SkillsController::class, 'getData'])->name('skills.getdata');

});
